name: Build python exe
on: workflow_dispatch
jobs:
  Run-PyInstaller:
    runs-on: ubuntu-latest
    steps:
      - name: PyInstaller Action
        uses: blockninja124/pyinstaller-action@002cf0572e6522daac3abd996ff236dffb5d9d89
        with:
          spec: main.py
          upload_exe_with_name: 'ValkModifierApp'
          options: --onefile, --windowed
