name: Build python exe
on: workflow_dispatch
jobs:
  Build-Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout root
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Run PyInstaller
        uses: blockninja124/pyinstaller-action@latest
        with:
          spec: main.py
          upload_exe_with_name: 'WindowsArtifact_${{github.run_id}}'
          upload_spec_file: false
          options: --onefile, --windowed, --icon valkyrienskies.ico
  Build-Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout root
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Run PyInstaller
        uses: blockninja124/pyinstaller-action@latest
        with:
          spec: main.py
          upload_exe_with_name: 'LinuxArtifact_${{github.run_id}}'
          upload_spec_file: false
          options: --onefile, --windowed, --icon valkyrienskies.ico
  Build-Mac:
    runs-on: macos-13
    steps:
      - name: Checkout root
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
      - name: Run PyInstaller
        uses: blockninja124/pyinstaller-action@latest
        with:
          spec: main.py
          upload_exe_with_name: 'MacArtifact_${{github.run_id}}'
          upload_spec_file: false
          options: --onefile, --windowed, --icon valkyrienskies.icns
