name: Build python exe
on: workflow_dispatch
jobs:
  Run-PyInstaller:
    runs-on: ubuntu-latest
    steps:
      - name: PyInstaller Action
        uses: blockninja124/pyinstaller-action@f0aaeb885829e891c3c774ecb524f4ae45c50364
        with:
          spec: main.py
          upload_exe_with_name: 'ValkModifierApp'
          options: --onefile, --windowed
